### ISSUE TITLE
pycharm Cannot find reference 'SUB' in '__init__.py

### ISSUE THREAD

**Issue by Xiang929** [zeromq/pyzmq#1191] opened 2018-07-10 10:30 UTC
Such as the title， All socket_types are not available, others are not automatically completed.
pycharm version: 2018.1.4
system: Window10
pyzmq version: 17.0

**Comment by Bobsans** [comment] 2018-07-25 13:02
+

**Comment by Bobsans** [comment] 2018-07-25 13:02
plus 1

**Comment by minrk** [comment] 2018-08-20 14:43
This is a duplicate of #1018. Static analysis cannot find runtime-defined names.

**Closed by minrk** 2018-08-20 14:43 UTC
