### ISSUE TITLE
asyncio IPC PUSH/PULL Socket.close + Context.term + Context.destroy do not reliably flush messages with LINGER == -1

### ISSUE THREAD

**Issue by thehesiod** [zeromq/pyzmq#832] opened 2016-04-12 00:12 UTC
libzmq-4.1.2
pyzmq-15.2.0
Python-3.5.1 (default, Dec 7 2015, 21:59:10) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]

HWM = 2

According to the docs if you set LINGER to -1, socket.close is supposed to flush out all messages before returning.  There are a few issues with this:

1. If socket.close / Context.destroy really were to flush the messages they should return futures
2. they do not actually wait for the the messages to get flushed.

I tried this with several messages of length ~700k and maybe 10% of the time the last two messages were not flushed.

If I add an asyncio.sleep after the term/destroy/close then the messages get flushed

**Comment by thehesiod** [comment] 2016-04-12 00:31
btw, the hack around this I'm currently using is sending a known marker socket.HWM + 1 times to flush out the local buffer.

**Comment by minrk** [comment] 2016-04-12 07:47
Can you provide some code to reproduce this? Socket.close should always return immediately, it never waits. LINGER governs when the *context* may discard messages, and it shouldn't if LINGER is -1. `Context.term` should block until all messages have been either delivered or discarded.

**Comment by thehesiod** [comment] 2016-04-12 07:48
I'll try to get a testcase working.  If Context.term truly did wait it would be a coroutine no?

**Comment by thehesiod** [comment] 2016-04-12 08:33
Here's a testcase, not it uses the default LINGER of -1.  Also from what I've seen the sleep in the receiver is necessary to trigger the issue.

```python
import zmq.asyncio
import zmq
import asyncio
import os
import pickle
import concurrent.futures

class Terminator:
    pass


class SocketCtx:
    def __init__(self, socket_type, high_water_mark, socket_name, connect_method_name):
        """
        Creates a ZMQ socket context object.  This class will send `high_water_mark` + 1
        `ZMQEmptyMsg`s to clear out the local cache since the LINGER parameter seems to
        be ignored: https://github.com/zeromq/pyzmq/issues/832

        :param socket_type: type of socket
        :param high_water_mark: high water mark
        :param socket_name: name to pass to connect_method
        :param connect_method_name: either "bind" or "connect"
        """
        self._zmq_ctx = None
        self._socket_type = socket_type
        self._socket_name = socket_name
        self._high_water_mark = high_water_mark
        self._connect_method_name = connect_method_name

    async def __aenter__(self):
        self._zmq_ctx = zmq.asyncio.Context()
        self._socket = self._zmq_ctx.socket(self._socket_type)
        self._socket.RCVHWM = self._socket.SNDHWM = self._high_water_mark
        getattr(self._socket, self._connect_method_name)(self._socket_name)

        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self._zmq_ctx:
            self._zmq_ctx.destroy()  # will close all sockets associated with context and (theoretically) linger until all data sent
            self._zmq_ctx = None
            self._socket = None

    async def recv(self, *args, **kwargs):
        return await self._socket.recv(*args, **kwargs)

    async def recv_pyobj(self, *args, **kwargs):
        data = await self._socket.recv(*args, **kwargs)
        pyobj = pickle.loads(data)
        return pyobj

    async def send(self, data):
        return await self._socket.send(data)

    async def send_pyobj(self, obj):
        pyobj = pickle.dumps(obj)
        return await self._socket.send(pyobj)


socket_name = 'ipc:///tmp/foobar'
def sender():
    loop = zmq.asyncio.ZMQEventLoop()
    asyncio.set_event_loop(loop)

    async def doit():
        async with SocketCtx(zmq.PUSH, 2, socket_name, 'connect') as zmq_socket:
            data = {y: {x: 140 for x in range(200)} for y in range(100)}

            total_sent = 0

            try:
                for i in range(25):
                    await zmq_socket.send_pyobj(data)
                    total_sent += len(data)
            except Exception as e:
                print(e)

        print("total sent:", total_sent)

    loop.run_until_complete(doit())


async def receiver(connected_event: asyncio.Event):

    async with SocketCtx(zmq.PULL, 2, socket_name, 'bind') as zmq_socket:
        connected_event.set()

        total_received = 0

        while True:
            try:
                pyobj = await zmq_socket.recv_pyobj()
                if isinstance(pyobj, Terminator):
                    break

                await asyncio.sleep(0.5)
                total_received += len(pyobj)
            except Exception as e:
                print(e)

    print("total received:", total_received)


async def main(loop):
    connected_event = asyncio.Event()
    recvr_task = asyncio.ensure_future(receiver(connected_event))
    await connected_event.wait()

    executor = concurrent.futures.ProcessPoolExecutor(1)
    await loop.run_in_executor(executor, sender)
    async with SocketCtx(zmq.PUSH, 2, socket_name, 'connect') as zmq_socket:
        await zmq_socket.send_pyobj(Terminator())

    await recvr_task


if __name__ == '__main__':
    _loop = zmq.asyncio.ZMQEventLoop()
    asyncio.set_event_loop(_loop)

    _loop.run_until_complete(main(_loop))
```

**Comment by minrk** [comment] 2016-04-12 09:53
Messages are not getting discarded by zmq in that example. That code is running afoul of the fact that zmq.PULL sockets fair-queue messages from their peers. The Terminator message from the second PUSH socket does not get queued after the *last* message from the sender, it is delivered ~immediately, ahead of any pending messages from the first PULL socket still in the queue.

If, for instance, you move the `Terminator` message to the end of the sender instead of a new socket, you can see that all messages are correctly delivered.

**Comment by thehesiod** [comment] 2016-04-13 00:11
So it two messages are in the in queue from two separate sockets, the newer one wins essentially? Is there any way to ensure ordering/priority?

**Comment by minrk** [comment] 2016-04-13 08:21
> So it two messages are in one PULL queue from two PUSH sockets, the most stale wins essentially?

No, it's fair-queued. If you have 5 messages pending from socket A and then 2 from socket B arrive, you will receive A, B, A, B, A, A, A.

> Is there any way to ensure ordering/priority?

Not across peers. If you want priority, you should use separate channels/sockets.

> Perhaps a solution would be when I get a Terminator, do a NO_BLOCK check to see if there are any other messages in the in_queue? Thoughts?

Flushing after the term signal is a good idea, and may work in this case, as long as you can guarantee that the Terminator isn't sent until all messages have been *delivered* by the other peer. I think you are right that NOBLOCK isn't working for asyncio sockets (fixed by #833), but for now you should be able to use `socket.poll(timeout=0)` to perform the same check.

**Comment by thehesiod** [comment] 2016-04-13 16:03
ok great thanks, I've updated my solution above per poll that I discovered independently which seems to be working in case others need it.  Let me know if you see any issues.  Thank again!

**Comment by minrk** [comment] 2016-04-13 18:24
Thanks!

**Comment by thehesiod** [comment] 2016-04-14 05:43
update: I've found with more testing that the polling solution I sent before does NOT reliably work (simplified above). So in this scenario I'm guaranteed that all the messages have been sent from socket A before the Terminator is sent from socket B (process with socket A has exited), however the receiver does not see all the messages sent before the Terminator in it's socket via poll.

This test seems sensitive to the receiver's HWM.  If the HWM is large (100), the test fails, if it's low (5), it succeeds. Something really strange is going on. So I'm re-opening this issue.

**Comment by thehesiod** [comment] 2016-04-14 06:09
I've added an option to enable sending "empty" messages to "flush" the PUSH socket.  I've noticed that if I just send 1 EmptyMsg things work as expected, but if I don't send any empty messages I don't see some of the items before the Terminator, where did it go?

**Comment by minrk** [comment] 2016-04-14 09:57
I can reproduce the lost message without asyncio, so I am fairly confident that it is a libzmq issue and not a pyzmq one. It appears that LINGER may not be being respected on the sender side, but I'm not sure.

**Comment by thehesiod** [comment] 2016-04-14 16:10
how do we proceed?

**Comment by thehesiod** [comment] 2016-04-14 18:14
I think I've verified that LINGER is broken.  If I sleep AFTER I destroy the socket the message is lost.  If I sleep BEFORE I close the socket the message is not lost.

**Comment by thehesiod** [comment] 2016-04-19 22:11
looks like this may have been fixed here: https://github.com/zeromq/libzmq/pull/1511.  Working on finding the best way to test it.

**Comment by thehesiod** [comment] 2016-04-20 01:05
reference for osx users who need the socket timeout fix, I've created a brew that builds libzmq HEAD against the 4-1 branch.  Can be used as follows: brew install thehesiod/tap/zeromq --HEAD

**Comment by thehesiod** [comment] 2016-04-20 02:10
I've now verified that both NOBLOCK + the flushing is working with pyzmq 15.3.0 and libzmq 4.1.5 so I'm closing this bug, thanks!

**Comment by minrk** [comment] 2016-04-20 08:08
Great, thanks @thehesiod!

**Comment by thehesiod** [comment] 2016-04-24 10:22
bad news, it's still happening :(

https://github.com/zeromq/libzmq/issues/1922

**Comment by thehesiod** [comment] 2016-08-23 00:35
still happening with latest binaries, seems to be a core bug

**Comment by minrk** [comment] 2016-08-23 08:18
Thanks. Closing in favor of the upstream libzmq bug, since it's confirmed there as not a pyzmq issue.

**Closed by minrk** 2016-08-23 08:18 UTC

**Comment by thehesiod** [comment] 2017-04-06 20:57
interesting update, seems like the latest pyzmq fixed this issue

**Comment by thehesiod** [comment] 2017-04-06 21:40
nevermind, it still happens, forgot it only happens on debian/ubuntu
