### ISSUE TITLE
pyzmq 17 asyncio hangs on exit

### ISSUE THREAD

**Issue by antonymayi** [zeromq/pyzmq#1167] opened 2018-04-13 10:39 UTC
after upgrading *just* pyzmq (same libzmq 4.2.5 and python 3.6.5 used in both cases) from 16.0.3 to 17.0 the following simple code runs to the end and then hangs forever while it was exiting ok before:

```
import asyncio
import zmq.asyncio

ctx = zmq.asyncio.Context()
pub = ctx.socket(zmq.PUB)
pub.bind('inproc://test')
sub = ctx.socket(zmq.SUB)
sub.connect('inproc://test')
sub.setsockopt(zmq.SUBSCRIBE, b'')

msg = b'foo', b'bar'

async def run():
    await pub.send_multipart(msg)
    assert msg == tuple(await sub.recv_multipart())
    print('DONE')

asyncio.get_event_loop().run_until_complete(run())
```

produces:
```
$ python xxx.py
DONE
```
and hangs forever.

couldn't find any notes suggesting I would need to change something when upgrading to 17.0 - so is this a bug?

**Comment by jvansanten** [comment] 2018-04-27 10:53
A random comment from the void: I can reproduce this. It appears that the sockets must be explicitly closed, otherwise their destructors hang forever in zmq/backend/cython/checkrc.pxd.

**Comment by minrk** [comment] 2018-04-30 11:16
This is a bug. An elusive one. The root cause of this is that a context has its `.term()` called during `__del__` before one or more of its sockets is closed. This will hang until the context is closed.

Closing sockets and contexts via garbage collection during process teardown has been a tricky issue since Python 3.4 changed how that works (in particular, it deliberately increased the randomness of order of the cleanup process).

I was able to reproduce this, and it turned out the `__dealloc__` is being called (which doesn't call `.close()`), but `__del__` is not (which does call close). So the fix should be #1173, which ensures that close is called in `__dealloc__` if it hasn't already been called by `__del__`.

The simplest workaround in the meantime is to call `ctx.destroy()` at the end of your script, which closes all sockets in order and terminates the context.

**Closed** 2018-05-02 08:04 UTC

**Comment by kalzoo** [comment] 2020-06-02 06:48
Still seeing this with `pyzmq==19.0.1`. Closing the socket (or destroying the context) fixes the problem, but it will be tricky to ensure that always happens. Here's the repro, FWIW. The "bug" is the hang at the end of script.

```
import asyncio
import logging
import zmq
import zmq.asyncio

# Yields a minimal amount of debug information
logging.basicConfig(level=logging.DEBUG)

# Set up our zmq socket
context = zmq.asyncio.Context()
socket = context.socket(zmq.DEALER)
socket.connect("tcp://not.real:12345")
socket.setsockopt(zmq.LINGER, 0)


def sync_worker():
    print("working!")
    loop.run_until_complete(socket.recv_multipart())


async def worker():
    # This line alone (uncommented) does not cause the bug
    # await asyncio.sleep(10)

    # This line alone does trigger the bug. This can't be fully cancelled and leaks some sort of
    # resource in the background which prevents the script from exiting.
    await socket.recv_multipart()


async def timeout_target():
    try:
        asyncio.create_task(worker())
        await asyncio.sleep(10)
    except Exception:
        print("cancelled!", flush=True)
        raise


loop = asyncio.get_event_loop()
try:
    # No bug with these two
    future = loop.run_in_executor(None, sync_worker)
    loop.run_until_complete(future)

    # This will cause the bug (unless socket.close() is called below)
    # loop.run_until_complete(asyncio.wait_for(timeout_target(), timeout=1))
except Exception as e:
    print(f"got exception {e}")

# This prevents the hang issue but also requires access to the socket...
# socket.close()

print("now the script will just hang...")

```

**Comment by sakurai-youhei** [comment] 2020-06-02 07:06
@kalzoo What about running `context.destroy()` through [atexit](https://docs.python.org/3/library/atexit.html) module?

```python
import atexit

...

context = zmq.asyncio.Context()
atexit.register(context.destroy)
```

**Comment by kalzoo** [comment] 2020-06-12 20:38
@sakurai-youhei , thanks for the reply! That's a good idea and would fix that repro script - but I'm finding that the event loop is hanging within a long-running application, where I don't easily have access to the context and sockets.
