### ISSUE TITLE
BUG: Unable to install in mac m1

### ISSUE THREAD

**Issue by iamshreeram** [zeromq/pyzmq#1912] opened 2023-11-30 14:29 UTC
### What pyzmq version?

25.1.1

### What libzmq version?

NA

### Python version (and how it was installed)

python 3.10

### OS

macOS Ventura 13.6

### What happened?

Seeing error while installing pyzmq; Below is the error - 

```
Building wheels for collected packages: markupsafe, pyzmq, pyyaml
  Building wheel for markupsafe (setup.py) ... done
  Created wheel for markupsafe: filename=MarkupSafe-2.1.3-py3-none-any.whl size=9757 sha256=31792d60bed54440b681565f3e13d5855d414d548d08842bf9002db50a3b92c3
  Stored in directory: /Users/ram/Library/Caches/pip/wheels/59/24/cf/b50b90b1cc2b8e08bf70c3e78590844039a1266fb95dcd9a6f
  Building wheel for pyzmq (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyzmq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [251 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying zmq/_typing.py -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/error.py -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/_future.py -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/asyncio.py -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/constants.py -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/decorators.py -> build/lib.macosx-10.9-arm64-pypy310/zmq
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/green
      copying zmq/green/device.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/green
      copying zmq/green/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/green
      copying zmq/green/core.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/green
      copying zmq/green/poll.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/green
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/green/eventloop
      copying zmq/green/eventloop/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/green/eventloop
      copying zmq/green/eventloop/ioloop.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/green/eventloop
      copying zmq/green/eventloop/zmqstream.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/green/eventloop
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/version.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/attrsettr.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/stopwatch.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/context.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/frame.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/tracker.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/poll.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/sugar/socket.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/auth
      copying zmq/auth/thread.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/auth
      copying zmq/auth/certs.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/auth
      copying zmq/auth/asyncio.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/auth
      copying zmq/auth/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/auth
      copying zmq/auth/ioloop.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/auth
      copying zmq/auth/base.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/auth
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_ioloop.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_version.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_monitor.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_security.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/conftest.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_decorators.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_etc.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_pubsub.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_auth.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_includes.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_mypy.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_future.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_zmqstream.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_message.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_cffi_backend.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_imports.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_socket.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_draft.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_asyncio.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_log.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_ssh.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_cython.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_retry_eintr.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_z85.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_error.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_reqrep.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_ext.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_multipart.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_context.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_proxy_steerable.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_device.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_pair.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_constants.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_monqueue.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_poll.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/tests/test_win32_shim.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/strtypes.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/monitor.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/win32.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/interop.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/jsonapi.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/z85.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/garbage.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/backend
      copying zmq/backend/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend
      copying zmq/backend/select.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/_poll.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/error.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/message.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/context.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/utils.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/socket.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cffi/devices.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/backend/cython/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/ssh
      copying zmq/ssh/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/ssh
      copying zmq/ssh/tunnel.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/ssh
      copying zmq/ssh/forward.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/ssh
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/eventloop
      copying zmq/eventloop/_deprecated.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/eventloop
      copying zmq/eventloop/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/eventloop
      copying zmq/eventloop/ioloop.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/eventloop
      copying zmq/eventloop/future.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/eventloop
      copying zmq/eventloop/zmqstream.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/eventloop
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/log
      copying zmq/log/handlers.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/log
      copying zmq/log/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/log
      copying zmq/log/__main__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/log
      creating build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      copying zmq/devices/monitoredqueue.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      copying zmq/devices/__init__.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      copying zmq/devices/monitoredqueuedevice.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      copying zmq/devices/proxydevice.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      copying zmq/devices/basedevice.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      copying zmq/devices/proxysteerabledevice.py -> build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      copying zmq/__init__.pyi -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/py.typed -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/__init__.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq
      copying zmq/sugar/__init__.pyi -> build/lib.macosx-10.9-arm64-pypy310/zmq/sugar
      copying zmq/tests/cython_ext.pyx -> build/lib.macosx-10.9-arm64-pypy310/zmq/tests
      copying zmq/utils/buffers.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/getpid_compat.h -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/pyversion_compat.h -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/zmq_compat.h -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/mutex.h -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/ipcmaxlen.h -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/config.json -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/utils/compiler.json -> build/lib.macosx-10.9-arm64-pypy310/zmq/utils
      copying zmq/backend/__init__.pyi -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend
      copying zmq/backend/cffi/_cdefs.h -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cffi
      copying zmq/backend/cython/message.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/backend/cython/libzmq.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/backend/cython/checkrc.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/backend/cython/__init__.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/backend/cython/context.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/backend/cython/socket.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/backend/cython/constant_enums.pxi -> build/lib.macosx-10.9-arm64-pypy310/zmq/backend/cython
      copying zmq/devices/monitoredqueue.pxd -> build/lib.macosx-10.9-arm64-pypy310/zmq/devices
      running build_ext
      running configure
      Using bundled libzmq
      already have bundled/zeromq
      already have platform.hpp
      generating cffi module 'build/temp.macosx-10.9-arm64-pypy310/zmq.backend.cffi._cffi.c'
      building 'zmq.libzmq' extension
      creating build/temp.macosx-10.9-arm64-pypy310/buildutils
      creating build/temp.macosx-10.9-arm64-pypy310/bundled
      creating build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq
      creating build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq/src
      g++ -pthread -arch arm64 -std=c++11 -pthread -arch arm64 -DNDEBUG -O2 -I/usr/local/opt/openjdk@11/include -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/ram/ram/apps/pypy/pypy3.10-v7.3.13-macos_arm64/include/pypy3.10 -c buildutils/initlibzmq.cpp -o build/temp.macosx-10.9-arm64-pypy310/buildutils/initlibzmq.o
      g++ -pthread -arch arm64 -std=c++11 -pthread -arch arm64 -DNDEBUG -O2 -I/usr/local/opt/openjdk@11/include -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/ram/ram/apps/pypy/pypy3.10-v7.3.13-macos_arm64/include/pypy3.10 -c bundled/zeromq/src/address.cpp -o build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq/src/address.o
      g++ -pthread -arch arm64 -std=c++11 -pthread -arch arm64 -DNDEBUG -O2 -I/usr/local/opt/openjdk@11/include -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/ram/ram/apps/pypy/pypy3.10-v7.3.13-macos_arm64/include/pypy3.10 -c bundled/zeromq/src/channel.cpp -o build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq/src/channel.o
      g++ -pthread -arch arm64 -std=c++11 -pthread -arch arm64 -DNDEBUG -O2 -I/usr/local/opt/openjdk@11/include -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/ram/ram/apps/pypy/pypy3.10-v7.3.13-macos_arm64/include/pypy3.10 -c bundled/zeromq/src/client.cpp -o build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq/src/client.o
      g++ -pthread -arch arm64 -std=c++11 -pthread -arch arm64 -DNDEBUG -O2 -I/usr/local/opt/openjdk@11/include -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/ram/ram/apps/pypy/pypy3.10-v7.3.13-macos_arm64/include/pypy3.10 -c bundled/zeromq/src/clock.cpp -o build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq/src/clock.o
      g++ -pthread -arch arm64 -std=c++11 -pthread -arch arm64 -DNDEBUG -O2 -I/usr/local/opt/openjdk@11/include -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/ram/ram/apps/pypy/pypy3.10-v7.3.13-macos_arm64/include/pypy3.10 -c bundled/zeromq/src/ctx.cpp -o build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq/src/ctx.o
      g++ -pthread -arch arm64 -std=c++11 -pthread -arch arm64 -DNDEBUG -O2 -I/usr/local/opt/openjdk@11/include -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/ram/ram/apps/pypy/pypy3.10-v7.3.13-macos_arm64/include/pypy3.10 -c bundled/zeromq/src/curve_client.cpp -o build/temp.macosx-10.9-arm64-pypy310/bundled/zeromq/src/curve_client.o
      In file included from bundled/zeromq/src/curve_client.cpp:35:
      In file included from bundled/zeromq/src/msg.hpp:40:
      In file included from bundled/zeromq/src/metadata.hpp:33:
      In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/map:2356:
      In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/functional:515:
      In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/boyer_moore_searcher.h:26:
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:372:5: error: static assertion failed due to requirement 'is_same<zmq::secure_allocator_t<unsigned char>, std::allocator<unsigned char>>::value': [allocator.requirements] states that rebinding an allocator to the same type should result in the original allocator
          static_assert(is_same<allocator_type, __rebind_alloc<__alloc_traits, value_type> >::value,
          ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:64:60: note: in instantiation of template class 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>' requested here
              std::vector<uint8_t, secure_allocator_t<uint8_t> > hello_plaintext (
                                                                 ^
      bundled/zeromq/src/curve_client_tools.hpp:110:60: error: no matching constructor for initialization of 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>')
              std::vector<uint8_t, secure_allocator_t<uint8_t> > welcome_plaintext (
                                                                 ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'int' to 'const std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>' for 1st argument
      class _LIBCPP_TEMPLATE_VIS vector
                                 ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'int' to 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>' for 1st argument
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
      In file included from bundled/zeromq/src/curve_client.cpp:38:
      In file included from bundled/zeromq/src/curve_client.hpp:37:
      bundled/zeromq/src/curve_client_tools.hpp:121:53: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              int rc = crypto_box_open (&welcome_plaintext[0], welcome_box,
                                         ~~~~~~~~~~~~~~~~~^~
      bundled/zeromq/src/curve_client_tools.hpp:129:47: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              memcpy (cn_server_, &welcome_plaintext[crypto_box_ZEROBYTES], 32);
                                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:130:47: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              memcpy (cn_cookie_, &welcome_plaintext[crypto_box_ZEROBYTES + 32],
                                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:154:60: error: no matching constructor for initialization of 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>')
              std::vector<uint8_t, secure_allocator_t<uint8_t> > vouch_plaintext (
                                                                 ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'int' to 'const std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>' for 1st argument
      class _LIBCPP_TEMPLATE_VIS vector
                                 ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'int' to 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>' for 1st argument
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
      In file included from bundled/zeromq/src/curve_client.cpp:38:
      In file included from bundled/zeromq/src/curve_client.hpp:37:
      bundled/zeromq/src/curve_client_tools.hpp:159:36: error: no member named 'begin' in 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>'
              std::fill (vouch_plaintext.begin (),
                         ~~~~~~~~~~~~~~~ ^
      bundled/zeromq/src/curve_client_tools.hpp:160:36: error: no member named 'begin' in 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>'
                         vouch_plaintext.begin () + crypto_box_ZEROBYTES, 0);
                         ~~~~~~~~~~~~~~~ ^
      bundled/zeromq/src/curve_client_tools.hpp:161:33: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              memcpy (&vouch_plaintext[crypto_box_ZEROBYTES], cn_public_, 32);
                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:162:33: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              memcpy (&vouch_plaintext[crypto_box_ZEROBYTES + 32], server_key_, 32);
                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:169:50: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
                crypto_box (vouch_box, &vouch_plaintext[0], vouch_plaintext.size (),
                                        ~~~~~~~~~~~~~~~^~
      bundled/zeromq/src/curve_client_tools.hpp:169:71: error: no member named 'size' in 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>'
                crypto_box (vouch_box, &vouch_plaintext[0], vouch_plaintext.size (),
                                                            ~~~~~~~~~~~~~~~ ^
      bundled/zeromq/src/curve_client_tools.hpp:177:60: error: no matching constructor for initialization of 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>')
              std::vector<uint8_t, secure_allocator_t<uint8_t> > initiate_plaintext (
                                                                 ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'size_t' (aka 'unsigned long') to 'const std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>' for 1st argument
      class _LIBCPP_TEMPLATE_VIS vector
                                 ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'size_t' (aka 'unsigned long') to 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>' for 1st argument
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:348:28: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
      In file included from bundled/zeromq/src/curve_client.cpp:38:
      In file included from bundled/zeromq/src/curve_client.hpp:37:
      bundled/zeromq/src/curve_client_tools.hpp:181:39: error: no member named 'begin' in 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>'
              std::fill (initiate_plaintext.begin (),
                         ~~~~~~~~~~~~~~~~~~ ^
      bundled/zeromq/src/curve_client_tools.hpp:182:39: error: no member named 'begin' in 'std::vector<unsigned char, zmq::secure_allocator_t<unsigned char>>'
                         initiate_plaintext.begin () + crypto_box_ZEROBYTES, 0);
                         ~~~~~~~~~~~~~~~~~~ ^
      bundled/zeromq/src/curve_client_tools.hpp:183:36: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              memcpy (&initiate_plaintext[crypto_box_ZEROBYTES], public_key_, 32);
                       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:184:36: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              memcpy (&initiate_plaintext[crypto_box_ZEROBYTES + 32], vouch_nonce + 8,
                       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:186:36: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
              memcpy (&initiate_plaintext[crypto_box_ZEROBYTES + 48],
                       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:189:40: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
                  memcpy (&initiate_plaintext[crypto_box_ZEROBYTES + 48 + 80],
                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/g++' failed with exit code 1
      ************************************************
      ************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
  Building wheel for pyyaml (pyproject.toml) ... done
  Created wheel for pyyaml: filename=PyYAML-6.0.1-pp310-pypy310_pp73-macosx_10_9_arm64.whl size=45374 sha256=4e9c05038e4ddb37153a43ba238a25e90b5679668c46f60d4140a6590bfa6b72
  Stored in directory: /Users/ram/Library/Caches/pip/wheels/e9/a3/45/ef86dd76c0fbc91ac46889a39d4710498896fe799f860db9ad
Successfully built markupsafe pyyaml
Failed to build pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
```

I have zeromq installed in my machine already.

**Comment by minrk** [comment] 2023-12-01 08:18
closing as duplicate of #1907

**Closed by minrk** 2023-12-01 08:18 UTC
