### ISSUE TITLE
recv and poll hangs with asyncio inside a multiprocessing child process

### ISSUE THREAD

**Issue by wannabesrevenge** [zeromq/pyzmq#1333] opened 2019-09-26 15:56 UTC
As the title states: recv and poll both hang when using the asyncio event loop inside of a multiprocessing child process. Here is a toy example that illustrates this problem:

```
import asyncio
import zmq
import zmq.asyncio
from multiprocessing import Process

zmqpath = "tcp://127.0.0.1:22222"

def parent():
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.PAIR)
    sock.bind(zmqpath)
    proc = Process(target=child)
    proc.start()

    async_loop = asyncio.get_event_loop()
    async_loop.create_task(parentloop(sock))
    async_loop.run_forever()

async def parentloop(sock):
    while True:
        msg = b"test"
        await sock.send(msg)
        print(f"sent {msg}")
        await asyncio.sleep(5)

def child():
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.PAIR)
    sock.connect(zmqpath)

    async_loop = asyncio.get_event_loop()
    async_loop.create_task(childloop(sock))
    async_loop.run_forever()

async def childloop(sock):
    while True:
        msg = await sock.recv()
        print(f"recv {msg}")

parent()
```

You can confirm with netstat and wireshark that the sockets are connected and the data is making it across the wire.

I have confirmed that Python 3.6 and 3.7 using pyzmq 18.1.0 are affected. The problem also occurs when using REQ/REP sockets. I version my python with pyenv and installed pyzmq using pipenv.

Personally, I have no idea how to debug this issue. I'm very new to asyncio, particularly when combined with pyzmq.

**Comment by wannabesrevenge** [comment] 2019-09-26 16:09
I did some testing and think I found the solution. The above example works if I comment out this line: https://github.com/zeromq/pyzmq/blob/master/zmq/asyncio/__init__.py#L79

I suspect that somewhere along the line, `_loop` is getting set to an asyncio event loop, and that is copied over to the multiprocessing child. Only a suspicion, I haven't confirmed it.

**Comment by wannabesrevenge** [comment] 2019-09-26 16:39
Ok, so I keep commenting and deleting comments because I keep seeing behavior change depending on my RNG luck.

Using python 3.7 (via pyenv), the toy program above sometimes works, and it sometimes doesn't work. This is like close to 50% works/doesn't work. If it doesn't work, then the recv hangs forever. If it does work, then the recv never hangs when there is a message to read. This must be some ZMQ state issue combined with multiprocessing?

**Comment by haverins** [comment] 2019-09-27 05:26
I see similar behaviour. If I add 2nd task to child process to generate some context switches, it usually works, but still not always.
```python
def child():
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.PAIR)
    sock.connect(zmqpath)

    async_loop = asyncio.get_event_loop()
    async_loop.create_task(childloop(sock))
    async_loop.create_task(generate_context_switches())
    async_loop.run_forever()

async def childloop(sock):
    while True:
        msg = await sock.recv()
        print(f"recv {msg}")

async def generate_context_switches():
    while True:
        await asyncio.sleep(0.1)
```

While it's not the root cause of problem here, I should mention that ZMQ documentation recommends against using PAIR sockets with TCP: http://api.zeromq.org/master:zmq-socket

**Comment by wannabesrevenge** [comment] 2019-09-27 16:30
found a work around for right now. I believe this has to do with this line here: https://github.com/zeromq/pyzmq/blob/master/zmq/asyncio/__init__.py#L28

Likely calling that method relies on some global state in asyncio that gets copied over to the new process. Here is the work around:

```
import asyncio
import zmq
import zmq.asyncio
from multiprocessing import Process
import time

zmqpath = "ipc:///tmp/fake_scok_test"

def parent():
    async_loop = asyncio.new_event_loop()
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.PAIR, io_loop=async_loop)
    sock.bind(zmqpath)
    proc = Process(target=child)
    proc.start()

    async_loop.create_task(parentloop(sock))
    async_loop.run_forever()

async def parentloop(sock):
    while True:
        msg = b"test"
        await sock.send(msg)
        print(f"sent {msg}")
        await asyncio.sleep(1)

def child():
    async_loop = asyncio.new_event_loop()
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.PAIR, io_loop=async_loop)
    sock.connect(zmqpath)
    print("child")

    async_loop.create_task(childloop(sock))
    async_loop.run_forever()

async def childloop(sock):
    while True:
        msg = await sock.recv()
        print(f"recv {msg}")

parent()
```

**Comment by wannabesrevenge** [comment] 2019-09-27 16:39
IMO, the async loop should be part of the context and passes the loop on to any sockets that get created from it

**Comment by minrk** [comment] 2024-02-29 13:45
Closing this, as creating async sockets outside event loops is not recommended as asyncio has itself deprecated `get_event_loop` when the event loop isn't running. Moving socket creation to the async part of the code (or via `loop.run_until_complete` doesn't have any issues:

```python
import asyncio
import zmq
import zmq.asyncio
from multiprocessing import Process

zmqpath = "tcp://127.0.0.1:22222"

def parent():
    proc = Process(target=child)
    proc.start()

    async_loop = asyncio.get_event_loop()
    async_loop.create_task(parentloop())
    async_loop.run_forever()

async def parentloop():
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.PAIR)
    sock.bind(zmqpath)
    while True:
        msg = b"test"
        await sock.send(msg)
        print(f"sent {msg}")
        await asyncio.sleep(5)

def child():
    async_loop = asyncio.get_event_loop()
    async_loop.create_task(childloop())
    async_loop.run_forever()

async def childloop():
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.PAIR)
    sock.connect(zmqpath)
    while True:
        msg = await sock.recv()
        print(f"recv {msg}")

if __name__ == "__main__":
    parent()
```

**Closed by minrk** 2024-02-29 13:45 UTC
