### ISSUE TITLE
Dll crash:Bad file descriptor (C:\\projects\\libzmq\\src\\epoll.cpp:100)

### ISSUE THREAD

**Issue by Godsix** [zeromq/pyzmq#1754] opened 2022-09-03 09:29 UTC
**Environment:**
OS:Windows 10 21H2 x64
Python version:3.10.6
pyzmq version:23.2.1
libzmq version:4.3.4
**Error Condition:**
1. Windows username contain non-ASCII characters,such as Chinese characters;
2. libzmq compile tool is msvc v142 or msvc v143,but v141 is OK;
I use pyzmq which is downloaded from pypi,it use libzmq-v142,it crashes,I compile pyzmq with libzmq-v141,it is OK,I compile libzmq with msvc-v143,and use it compile pyzmq,it crashes too.

**Error:**
Dll crashes:"Bad file descriptor (E:\OpenSource\libzmq\src\epoll.cpp:100)" or "Bad file descriptor (C:\\projects\\libzmq\\src\\epoll.cpp:100)",it indicates crash at src\epoll.cpp, line 100

**Comment by minrk** [comment] 2022-09-07 11:30
Thanks for reporting details! I've never been able to reproduce this bug (tracked as #1505) because the wheels always work for me.

It appears to be a bug in libzmq: https://github.com/zeromq/libzmq/pull/4386 Do any notes there help you?

I'll close this as a duplicate of #1505, keeping this  for further detail.

**Closed** 2022-09-07 11:30 UTC
