### ISSUE TITLE
async poll/recv_multipart block on last message

### ISSUE THREAD

**Issue by jsmitchell** [zeromq/pyzmq#1065] opened 2017-08-25 20:32 UTC
I am seeing strange behavior on both the 17.0.0b1 release and on current master (as of commit 5678f964e). Code which works using the existing zmq.asyncio.ZMQEventLoop under 16.0.2 seems to hang on the last message received. In other words, neither recv_multipart() nor poll() yield to notify of the last message on the socket (or so it appears). If additional messages are delivered to the socket, those blocking calls return and progress is made. Strangely, if I put a `yield from asyncio.sleep()` in the receive method and set the zmq.NOBLOCK flag on recv_multipart() (with a try except continue for the empty response), the last message is received and processed.

I also tried swapping the eventloop implementations for both standard asyncio and uvloop, with no change in behavior.

**Comment by minrk** [comment] 2017-08-27 00:24
Do you have an example to test with? When you say the last message, do you mean a whole multi-part message fails to arrive, or the first N-1 frames of a multipart message arrive, and the last frame never does?

**Comment by jsmitchell** [comment] 2017-08-28 00:16
The example is complicated. I will see if I can simplify it, but it currently involves conversation with a separate client implemented in go. Up to now I have tried both `yield from recv_multipart()` and `yield from poll()`, neither of which return from the blocking call for that last multipart message. They behave as expected for all multipart messages up to the last message. I'll see if I can inspect the frames to see if a partial message is arriving, but I would expect that would return from poll() on zmq.POLLIN regardless.

**Comment by minrk** [comment] 2017-08-28 16:47
This is exactly the symptom I would expect if we've handled events a little bit wrong with the new poll integration. These can be pretty tricky to reproduce reliably, so if you can produce a test case, that would be extremely helpful.

**Comment by jsmitchell** [comment] 2017-08-30 17:15
The breakage is introduced on commit `f2457b3`. It looks to me like it gets into a situation where the _schedule_remaining_events() _handle_events() task scheduling breaks, and therefore there are no scheduled tasks to handle new events. The behavior is that a large number of messages are sent all at once and then no receive events are handled (because neither _schedule_remaining_events() or _handle_events() are scheduled tasks any longer). If I call self._add_io_state(self._WRITE) at the end of _add_send_event() regardless of whether self._send_futures has items, then things work as expected.

**Comment by jsmitchell** [comment] 2017-08-30 17:21
I'm not suggesting that is the correct fix, as it seems to perform poorly, but it may shed light on the issue.

**Comment by minrk** [comment] 2017-08-31 11:49
Thanks! I'll look into it when I get a chance. If you have a test script that reproduces the failure, I should be able to track it down.

**Comment by costrouc** [comment] 2017-10-10 14:50
@jsmitchell thank you for raising this issue. I have had this exact same issue and found this after about 2 days worth of trying to figure out why pyzmq was hanging. I was using 17.0.0b1 and downgrading to 16.0.2 fixed the issues I was having.

While is around 300 lines of code I have included a [gist](https://gist.github.com/costrouc/44b5dbcd7783c9b0fb3a95f065f577d4) that can reproduce the issue. I was implementing an asyncio version of the Majordomo Protocol. The issue non deterministically occurs when the scheduler sends all the tasks to workers (last message). The socket then appears to freeze. Workers do not receive the messages sent by the scheduler and the scheduler does not receive heartbeats from the workers. Since the workers do not receive a heartbeat response they assume the scheduler is dead and disconnect then reconnect. Then the schedulers sees some messages were lost and the sends them back to workers (cycle continues).

Not sure above is helpful (since I know this is a lot of code) but I am experiencing the same issue and it  looks like you needed code to reproduce the issue. `python main.py` should run the test. `[ Client  ]` done indicates that all the messages were processed by the workers. Here is the example output with two pyzmq versions

Hangs using pyzmq 17.0.0b1 (even using uvloop and default event loop). You have to run this several times until it hangs (sometimes it doesn't). But if you crank up the number of messages say 1000 it will always hang. HANGS HERE FOR TIMEOUT indicates where the programs hangs. 
``` bash
INFO:mdp.worker:connecting ZMQ socket to tcp://0.0.0.0:8000
INFO:mdp.scheduler:Binding ZMQ socket client to tcp://0.0.0.0:8000
INFO:mdp.client:Connecting ZMQ socket to tcp://0.0.0.0:8000
[ Client  ] 1 jobs submitted
[ Client  ] 2 jobs submitted
[ Client  ] 3 jobs submitted
[ Client  ] 4 jobs submitted
[ Client  ] 5 jobs submitted
[ Client  ] 6 jobs submitted
[ Client  ] 7 jobs submitted
[ Client  ] 8 jobs submitted
[ Client  ] 9 jobs submitted
[ Client  ] 10 jobs submitted
INFO:mdp.scheduler:adding worker b'\x00k\x8bEh' for service b'hello.world'
[Scheduler] Count 1 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 2 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 3 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 4 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 5 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 6 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 7 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 8 sent to worker b'\x00k\x8bEh'
[Scheduler] Count 9 sent to worker b'\x00k\x8bEh'
[ Worker  ] processing message 1
[ Worker  ] Counter     1 completed Queue size:     6
[ Worker  ] processing message 2
[Scheduler] Count 10 sent to worker b'\x00k\x8bEh'
[ Worker  ] Counter     2 completed Queue size:     5
[ Worker  ] processing message 3
[ Worker  ] Counter     3 completed Queue size:     4
[ Worker  ] processing message 4
[ Worker  ] Counter     4 completed Queue size:     3
[ Worker  ] processing message 5
[ Worker  ] Counter     5 completed Queue size:     2
[ Worker  ] processing message 6
[ Worker  ] Counter     6 completed Queue size:     1
[ Worker  ] processing message 7
[ Worker  ] Counter     7 completed Queue size:     0
INFO:mdp.worker:no response from broker in 10 seconds -- reconnecting
INFO:mdp.worker:disconnecting zmq socket from tcp://0.0.0.0:8000
INFO:mdp.worker:connecting ZMQ socket to tcp://0.0.0.0:8000
[Scheduler] message done from worker b'\x00k\x8bEh' for client b'\x00k\x8bEg'
[Scheduler] message done from worker b'\x00k\x8bEh' for client b'\x00k\x8bEg'
[ Client  ] 1 jobs completed
INFO:mdp.scheduler:adding worker b'\x00k\x8bEi' for service b'hello.world'
[Scheduler] message done from worker b'\x00k\x8bEh' for client b'\x00k\x8bEg'
[ Client  ] 2 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEh' for client b'\x00k\x8bEg'
[ Client  ] 3 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEh' for client b'\x00k\x8bEg'
[ Client  ] 4 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEh' for client b'\x00k\x8bEg'
[ Client  ] 5 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEh' for client b'\x00k\x8bEg'
[ Client  ] 6 jobs completed
[ Client  ] 7 jobs completed     !!!HANGS HERE FOR HEARTBEAT TIMEOUT!!!
INFO:mdp.scheduler:removing worker b'\x00k\x8bEh' for service b'hello.world' - rescheduling 3 messages
[Scheduler] Count 11 sent to worker b'\x00k\x8bEi'
[Scheduler] Count 12 sent to worker b'\x00k\x8bEi'
[Scheduler] Count 13 sent to worker b'\x00k\x8bEi'
[ Worker  ] processing message 8
[ Worker  ] Counter     8 completed Queue size:     0
[Scheduler] message done from worker b'\x00k\x8bEi' for client b'\x00k\x8bEg'
[ Worker  ] processing message 9
[ Worker  ] Counter     9 completed Queue size:     1
[ Worker  ] processing message 10
[ Worker  ] Counter    10 completed Queue size:     0
[ Client  ] 8 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEi' for client b'\x00k\x8bEg'
[Scheduler] message done from worker b'\x00k\x8bEi' for client b'\x00k\x8bEg'
[ Client  ] 9 jobs completed
[ Client  ] 10 jobs completed
[ Client  ] === DONE ===
```

Successful using pyzmq 16.0.2 
``` bash
INFO:mdp.worker:connecting ZMQ socket to tcp://0.0.0.0:8000
INFO:mdp.scheduler:Binding ZMQ socket client to tcp://0.0.0.0:8000
INFO:mdp.client:Connecting ZMQ socket to tcp://0.0.0.0:8000
[ Client  ] 1 jobs submitted
[ Client  ] 2 jobs submitted
[ Client  ] 3 jobs submitted
[ Client  ] 4 jobs submitted
[ Client  ] 5 jobs submitted
[ Client  ] 6 jobs submitted
[ Client  ] 7 jobs submitted
[ Client  ] 8 jobs submitted
[ Client  ] 9 jobs submitted
[ Client  ] 10 jobs submitted
INFO:mdp.scheduler:adding worker b'\x00k\x8bEg' for service b'hello.world'
[Scheduler] Count 1 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 2 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 3 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 4 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 5 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 6 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 7 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 8 sent to worker b'\x00k\x8bEg'
[Scheduler] Count 9 sent to worker b'\x00k\x8bEg'
[ Worker  ] processing message 1
[ Worker  ] Counter     1 completed Queue size:     5
[Scheduler] Count 10 sent to worker b'\x00k\x8bEg'
[ Worker  ] processing message 2
[ Worker  ] Counter     2 completed Queue size:     4
[ Worker  ] processing message 3
[ Worker  ] Counter     3 completed Queue size:     3
[ Worker  ] processing message 4
[ Worker  ] Counter     4 completed Queue size:     2
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Worker  ] processing message 5
[ Worker  ] Counter     5 completed Queue size:     1
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Worker  ] processing message 6
[ Worker  ] Counter     6 completed Queue size:     0
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Client  ] 1 jobs completed
[ Client  ] 2 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Worker  ] processing message 7
[ Worker  ] Counter     7 completed Queue size:     3
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Worker  ] processing message 8
[ Worker  ] Counter     8 completed Queue size:     2
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Client  ] 3 jobs completed
[ Worker  ] processing message 9
[ Client  ] 4 jobs completed
[ Worker  ] Counter     9 completed Queue size:     1
[ Client  ] 5 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Client  ] 6 jobs completed
[ Worker  ] processing message 10
[ Worker  ] Counter    10 completed Queue size:     0
[ Client  ] 7 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Client  ] 8 jobs completed
[Scheduler] message done from worker b'\x00k\x8bEg' for client b'\x00k\x8bEh'
[ Client  ] 9 jobs completed
[ Client  ] 10 jobs completed
[ Client  ] === DONE ===
```

**Comment by minrk** [comment] 2017-11-09 12:03
Thanks for the test case! I finally managed to spend some time testing, and this ought to be fixed by #1107.

**Closed** 2017-11-10 11:38 UTC

**Comment by jsmitchell** [comment] 2017-11-10 18:54
I have tested this and can confirm it fixes the issue. Thanks @minrk !

**Comment by costrouc** [comment] 2017-11-11 00:45
Tested and it works for me as well. Thank you @minrk!
