### ISSUE TITLE
asyncio creation/assignment ordering

### ISSUE THREAD

**Issue by jimrthy** [zeromq/pyzmq#985] opened 2017-02-24 19:44 UTC
This may just be a documentation issue, really.

zmq.version = 4.1.6
pyzmq_version = 16.0.2
sys.version = 3.5.2 (default, Nov 17, 2016, 17:05:23)
[GCC 5.4.0 20160609]

This is really just a standard vanilla ubuntu 16.04 installation where I installed python3 via apt and zmq using pip.

I'm really just one step past following along with the basic examples (which worked fine). Actually, the code is almost a direct copy/paste from there.

I'm trying to break the steps up into a chain of classes and function calls that make sense with our architecture. It isn't much more complicated than: Set up the context, the asyncio loop, a couple of sockets, and try to `yield from sock.poll(500)`

When I try to read from or poll a socket, I sometimes get a ValueError from zmq/asyncio/__init__.py, line 294, in _add_io_state that works its way down through 
asyncio.selector_events line 234, in add_reader
eventually down to selectors.py, line 39 in _fileobj_to_fd.

I apologize for not having a full stack trace and the actual code handy. Corporate legal stuff.

I spent all afternoon yesterday trying to figure out the difference between what worked and what didn't. The annoying part is that sometimes it worked fine.

I just realized that the difference depends on when I set the pieces up.

This works:
a. Create ioloop
b. Assign ioloop
c. Create context and sockets
d. Connect sockets
e. Set up the reader coroutine to handle all my incoming messages
f. Call ioloop.create_task() on the future that returns
g. Set up a writer coroutine to send out a request
h. Call asyncio.gather() on that future and the task from step e
i. Call ioloop.run_until_complete() on whatever it is that returns

(I'm also new to asyncio, so this probably isn't the best way to set this up. It just happens to be the first approach that worked).

This [mostly] doesn't:
a. Create ioloop
b. Create context and sockets
c. Assign ioloop
d. Connect sockets
(the rest is the same)

I'm not absolutely 100% sure that this is the root cause of my problem, since I had a couple of false positives yesterday. But this is the first difference I've found that 
a) seems to make it succeed reliably
b) actually seems like a reasonable probable cause

Just in case this is also a factor, that ubuntu instance is actually a VirtualBox VM running on a Mac.

**Comment by minrk** [comment] 2017-02-26 15:02
Yes, this is generally true with asyncio, as creating objects associated with asyncio eventloops bind references to the current eventloop when the objects are created (the `Create context and sockets` step). Changing the eventloop means that those objects are still associated with a certain eventloop, which you don't end up running. The issue seems to mainly be caused by the lack of an informative error when binding to an eventloop that won't work, which should be fixed by #988.

If you have code like:

```python
import asycio
import zmq
import zmq.asyncio

loop = zmq.asyncio.ZMQEventLoop()
ctx = zmq.asyncio.Context()
sock = ctx.socket(zmq.PUB) # <- this line will connect to asyncio.get_event_loop()

asyncio.set_event_loop(loop)
```

Creating the socket would hook up to the current eventloop. After #988, this will check the type of the eventloop, and raise an error if it's not zmq's eventloop implementation.

**Closed** 2017-03-08 19:31 UTC
