### ISSUE TITLE
recv() fails after poll() returns nonzero

### ISSUE THREAD

**Issue by zpincus** [zeromq/pyzmq#1325] opened 2019-09-09 20:45 UTC
I have been getting sporadic `zmq.error.Again` errors on `socket.recv()` after `socket.poll()` returns a nonzero value.

This seems impossible --`poll()` should only return nonzero if there are bytes ready to `recv()`, right? But if `recv()` is failing with EAGAIN, that means no bytes are ready, right?

Is this a pyzmq or a libzmq problem? How best to diagnose? Or am I thinking about this wrong?

Here is simplified code illustrating the situation. In reality it runs in a background thread, waiting to service network requests, until the `RUNNING` flag gets set to tell the thread to stop running.

```python
context = zmq.Context()
socket = context.socket(zmq.REP)
socket.RCVTIMEO = 0
socket.bind(address)
RUNNING = True

def mainloop():
    while RUNNING:
        while not socket.poll(500):
            # every 500 ms, check if still running while we wait for data
            if not RUNNING:
                return
        message = socket.recv()
        # ... service message ...

mainloop()
```

Sometimes this crashes out with the following error:
```
    message =socket.recv()
  File "zmq/backend/cython/socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable
```

This has happened on systems with pyzmq 18.0.1 as well as 17.1.2, using libzmq 4.3.1 (compiled from source).

**Comment by tau-mask** [comment] 2020-03-20 01:53
I've been experiencing the same issue, but I have no clue how to debug the code. Here's how to reproduce it:

- requires a `REP` socket open, with polling (using a `zmq.Poller()` object also triggers the bug)
- send a few dozen random bytes (no `\0` inside) through TCP/IP

The socket is then erroneously marked as having data ready to read. If you use a blocking `recv()`, the program will block indefinitely. If you use a non-blocking `recv()`, you get a `zmq.error.Again` and the contents are cleared.

As a workaround, I thus use a non-blocking `recv()` and an `except zmq.error.Again:` statement, but I can afford it because my TCP messages are small and sent in just one packet. It is possible that larger messages will fail entirely.

**Comment by minrk** [comment] 2021-02-18 11:38
if poll is returning a POLLIN state when there's nothing to recv, this would definitely be a question for libzmq.

Another way to do the same pattern above would be to skip the poll, and jut call recv with a timeout:

```python
socket.RCVTIMEO = 500 # 500ms
while RUNNING:
    try:
        # blocks up to RCVTIMEO
        message = socket.recv()
    except zmq.Again:
        # no message
        pass
```

I will note that it's ~never a good idea to use REQ/REP in production as the lock-step request/reply loop makes error handling impossible. Instead, use ROUTER/DEALER.

**Closed by minrk** 2021-02-18 11:38 UTC
