### ISSUE TITLE
Starting `zmq.asyncio.Poller` with socket initialized outside of running loop hangs

### ISSUE THREAD

**Issue by arandomliz** [zeromq/pyzmq#1558] opened 2021-07-07 16:01 UTC
I've found some interesting behavior, that should probably be mentioned in the documentation. The gist is: When using `zmq.asyncio.Poller.poll`, one must create the socket(s) inside a running `asyncio` loop, otherwise `zmq.asyncio.Poller.poll` is prone to hanging. The hanging can be fixed using a timeout, but it is still very much annoying. Weirdly enough the poller will return a received event after the timeout. 

An interesting observation: I discovered this 'bug' whilst translating the tornado based `llbroker3.py` from the ØMQ guide into `asyncio` code. At first I couldn't reliably reproduce the error. It was kinda random. But the moment I set the amount of parallel workers to one, I was able to reproduce this error consistently. I'm still not sure why it worked sometimes with multiple workers.

This example is as minimal as I was able to get it
```python
from threading import Thread
import logging
import time
import zmq

import asyncio
import zmq.asyncio 

setup_inside_running_loop = False  # Change this value to see the differing behavior

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s %(message)s"
)


def worker_task(worker_url, ident, ctx = None):
    """Worker task, using a REQ socket to do load-balancing."""
    socket = (ctx or zmq.Context.instance()).socket(zmq.REQ)
    socket.identity = f"Worker-{ident}".encode("ascii")
    socket.connect(worker_url)

    # Send request, get reply
    socket.send(b"READY")

    while True:
        request = socket.recv()
        logging.info(f"{socket.identity.decode('ascii')}: {request.decode('ascii')}")
        socket.send(b"Ok")


async def start_polling(backend):
    poller = zmq.asyncio.Poller()
    poller.register(backend, zmq.POLLIN)

    while True:
        logging.info("Starting poll")
        s = time.time()
        socks = dict(await poller.poll(1000))
        e = time.time()
        logging.info(f"End Polling {e-s:.2f}s (ret: {socks})")

        if e - s > 0.8:
            logging.info("##### Used timeout")

        if backend in socks:
            await backend.recv()
            await backend.send(b"test")


url_worker = "ipc://backend.ipc"

# Start background tasks
Thread(target=worker_task, args=(url_worker, 0), daemon=True).start()

ctx = zmq.asyncio.Context()
backend = None if setup_inside_running_loop else ctx.socket(zmq.REP)  # Outside of running asyncio.loop 

async def startup():
    global backend

    if backend is None:  # Inside of it
        backend = ctx.socket(zmq.REP)
    backend.bind(url_worker)

    await start_polling(backend)

asyncio.run(startup())
```

**Comment by minrk** [comment] 2021-07-08 13:33
Thanks for the test case! This is a duplicate of #1547 and #1255 and #1296 and fixed by #1551.

**Closed by minrk** 2021-07-08 13:33 UTC
